### ISSUE TITLE
npm deploy warnings

### ISSUE THREAD

**Issue by shakaran** [NeoRazorX/facturascripts#272]
Task for future:

```cli
 npm install
facturascripts@1.0.0 someroute/facturascripts.git
├── bootbox@4.4.0 
├── UNMET PEER DEPENDENCY bootstrap@4.0.0-beta.2
├─┬ bootstrap-fileinput@4.4.6 
│ └── bootstrap@3.3.7 
├── font-awesome@4.7.0 
├─┬ handsontable@0.34.5 
│ ├── moment@2.18.1 
│ ├── numbro@1.11.0 
│ └── pikaday@1.5.1 
├── jquery@3.2.1 
├── jquery-ui-dist@1.12.1 
├── jscolor-picker@2.0.4 
└── popper.js@1.13.0 

npm WARN bootstrap-fileinput@4.4.6 requires a peer of bootstrap@>= 3.0.0 but none was installed.

```

- [ ] UNMET PEER DEPENDENCY bootstrap@4.0.0-beta.2
- [ ] bootstrap-fileinput

**Comment by shawe** [comment]
@shakaran this seems to be a bug on bootstrap-fileinput, on it's github account (https://github.com/kartik-v/bootstrap-fileinput) says:

An enhanced HTML 5 file input for Bootstrap 3.x and 4.x with file preview for various files, offers multiple selection, and more. 

For me, seems to a bad internal dependency.

**Comment by shawe** [comment]
boostrap-fileinput was deleted from package.json and now seems to not throw warning messages.

I supose that maybe this https://getbootstrap.com/docs/4.0/components/input-group/#custom-file-input will be the native alternative without external libraries. But at least, require to be changed on AdminHome -> Add modal because was trying to load fileinput.

**Comment by shakaran** [comment]
Ok, fixed to me. So closing ;) Thanks
